import { generateOpenAIText, getAIDiagnostic, parseJsonResponse, OpenAIDiagnosticError } from "./_openai.js";
import { LearnerSnapshot, learnerContext, missionTeacherInstructions } from "./eduquestTeacher.js";
import { CatalogWord, getCatalogWords, LearningCatalogError } from "./learningCatalog.js";

const allowedTypes = new Set(["multiple-choice", "arrange-words", "fill-blank", "match-pairs", "writing-challenge"]);

const missionJsonSchema = {
  type: "json_schema", name: "eduquest_adaptive_mission", strict: true,
  schema: { type: "object", additionalProperties: false, required: ["lesson"], properties: { lesson: { type: "object", additionalProperties: false, required: ["unitId", "unitTitle", "title", "description", "icon", "xpReward", "exercises", "vocabulary"], properties: {
    unitId: { type: "string" }, unitTitle: { type: "string" }, title: { type: "string" }, description: { type: "string" }, icon: { type: "string" }, xpReward: { type: "number" },
    exercises: { type: "array", minItems: 3, maxItems: 5, items: { type: "object", additionalProperties: false, required: ["type", "prompt", "options", "correctAnswer", "leftPairs", "rightPairs", "writingPrompt", "audioText", "translationContext"], properties: { type: { type: "string", enum: ["multiple-choice", "arrange-words", "fill-blank", "match-pairs", "writing-challenge"] }, prompt: { type: "string" }, options: { type: "array", items: { type: "string" } }, correctAnswer: { type: "string" }, leftPairs: { type: "array", items: { type: "string" } }, rightPairs: { type: "array", items: { type: "string" } }, writingPrompt: { type: "string" }, audioText: { type: "string" }, translationContext: { type: "string" } } } },
    vocabulary: { type: "array", minItems: 3, maxItems: 6, items: { type: "object", additionalProperties: false, required: ["word", "translation", "example", "exampleTranslation", "category"], properties: { word: { type: "string" }, translation: { type: "string" }, example: { type: "string" }, exampleTranslation: { type: "string" }, category: { type: "string" } } } }
  } } } }
} as const;

class InvalidMissionError extends Error { constructor(message: string) { super(message); this.name = "InvalidMissionError"; } }
function shuffled<T>(items: T[]) { return [...items].sort(() => Math.random() - 0.5); }
function catalogLesson(words: CatalogWord[], suffix: string, level: number) {
  const [first, second, third, fourth = first] = words;
  const distractors = shuffled(words.filter((word) => word.id !== first.id).map((word) => word.translation)).slice(0, 3);
  const sentenceWords = first.example.replace(/[.!?]/g, "").split(/\s+/).filter(Boolean);
  return { id: `catalog-mission-${suffix}`, unitId: `catalog-${first.category.toLowerCase().replace(/\W+/g, "-")}`, unitTitle: `Inglês ${level <= 2 ? "essencial" : "em prática"}`, title: `Missão: ${first.category}`, description: `Aprenda e pratique palavras sobre ${first.category.toLowerCase()}.`, icon: "🗺️", xpReward: 80, catalogContentIds: words.map((word) => word.id), exercises: [
    { id: `catalog-${suffix}-1`, type: "multiple-choice", prompt: `O que significa “${first.word}”?`, options: shuffled([first.translation, ...distractors]), correctAnswer: first.translation, leftPairs: [], rightPairs: [], writingPrompt: "", audioText: first.word, translationContext: first.translation },
    { id: `catalog-${suffix}-2`, type: "fill-blank", prompt: `Complete a frase: ${second.example.replace(second.word, "____")}`, options: shuffled([second.word, first.word, third.word]), correctAnswer: second.word, leftPairs: [], rightPairs: [], writingPrompt: "", audioText: second.example, translationContext: second.exampleTranslation },
    { id: `catalog-${suffix}-3`, type: "arrange-words", prompt: "Organize as palavras para formar a frase em inglês.", options: shuffled(sentenceWords), correctAnswer: sentenceWords.join(" "), leftPairs: [], rightPairs: [], writingPrompt: "", audioText: first.example, translationContext: first.exampleTranslation },
    { id: `catalog-${suffix}-4`, type: "match-pairs", prompt: "Ligue cada palavra em inglês à sua tradução.", options: [], correctAnswer: "", leftPairs: [first.word, second.word, third.word], rightPairs: [first.translation, second.translation, third.translation], writingPrompt: "", audioText: "", translationContext: "" },
    { id: `catalog-${suffix}-5`, type: "writing-challenge", prompt: `Escreva uma frase curta usando “${fourth.word}”.`, options: [], correctAnswer: "", leftPairs: [], rightPairs: [], writingPrompt: `Escreva uma frase curta em inglês usando a palavra “${fourth.word}”.`, audioText: "", translationContext: fourth.exampleTranslation }
  ], vocabulary: words.map(({ word, translation, example, exampleTranslation, category }) => ({ word, translation, example, exampleTranslation, category })) };
}
function normalizeLesson(raw: any, suffix: string) {
  const lesson = raw?.lesson;
  if (!lesson || !Array.isArray(lesson.exercises) || lesson.exercises.length < 3 || lesson.exercises.length > 5) throw new InvalidMissionError("A missão precisa conter entre 3 e 5 exercícios.");
  const exercises = lesson.exercises.map((exercise: any, index: number) => { const label = `Exercício ${index + 1}`; if (!allowedTypes.has(exercise?.type)) throw new InvalidMissionError(`${label}: tipo inválido.`); if (typeof exercise?.prompt !== "string" || !exercise.prompt.trim()) throw new InvalidMissionError(`${label}: enunciado ausente.`); if (exercise.type === "writing-challenge" && (typeof exercise.writingPrompt !== "string" || !exercise.writingPrompt.trim())) throw new InvalidMissionError(`${label}: writingPrompt ausente.`); if (["multiple-choice", "fill-blank", "arrange-words"].includes(exercise.type) && (!Array.isArray(exercise.options) || typeof exercise.correctAnswer !== "string")) throw new InvalidMissionError(`${label}: opções inválidas.`); if (exercise.type === "match-pairs" && (!Array.isArray(exercise.leftPairs) || !Array.isArray(exercise.rightPairs) || exercise.leftPairs.length < 2 || exercise.leftPairs.length !== exercise.rightPairs.length)) throw new InvalidMissionError(`${label}: pares incompletos.`); return { ...exercise, id: `ai-${suffix}-${index + 1}`, correctAnswer: exercise.type === "writing-challenge" ? "" : exercise.correctAnswer }; });
  if (!Array.isArray(lesson.vocabulary) || lesson.vocabulary.length < 3) throw new InvalidMissionError("Baú: a missão precisa trazer de 3 a 6 palavras novas.");
  const vocabulary = lesson.vocabulary.map((item: any, index: number) => { const fields = ["word", "translation", "example", "exampleTranslation", "category"]; const invalid = fields.find((field) => typeof item?.[field] !== "string" || !item[field].trim()); if (invalid) throw new InvalidMissionError(`Baú, palavra ${index + 1}: campo '${invalid}' ausente.`); return { word: item.word.trim(), translation: item.translation.trim(), example: item.example.trim(), exampleTranslation: item.exampleTranslation.trim(), category: item.category.trim() }; });
  return { id: `ai-mission-${suffix}`, unitId: typeof lesson.unitId === "string" ? lesson.unitId : "adaptive-mission", unitTitle: typeof lesson.unitTitle === "string" ? lesson.unitTitle : "Missão adaptativa", title: typeof lesson.title === "string" ? lesson.title : "Nova missão", description: typeof lesson.description === "string" ? lesson.description : "Uma missão criada para o seu momento de aprendizado.", icon: typeof lesson.icon === "string" ? lesson.icon : "🚀", xpReward: Math.min(120, Math.max(60, Number(lesson.xpReward) || 80)), exercises, vocabulary };
}
export default async function handler(req: any, res: any) {
  if (req.method !== "POST") return res.status(405).json({ error: "Método não permitido." });
  const { age, ageGroup, userLevel = 1, goal, previousLessonTitle, completedLessonTitles = [], knownWords = [] } = req.body || {};
  if (!Number.isFinite(Number(age)) || !["kids", "teens"].includes(ageGroup)) return res.status(400).json({ error: "Perfil do aluno inválido para criar a missão." });
  const learner: LearnerSnapshot = { age: Number(age), ageGroup, level: Number(userLevel), goal: typeof goal === "string" ? goal : "aprender inglês", completedLessonTitles: Array.isArray(completedLessonTitles) ? completedLessonTitles.filter((value): value is string => typeof value === "string") : [], knownWords: Array.isArray(knownWords) ? knownWords.filter((value): value is string => typeof value === "string") : [] };
  try {
    try { const catalog = await getCatalogWords({ userLevel: learner.level, knownWords: learner.knownWords, amount: 5 }); return res.status(200).json({ lesson: catalogLesson(catalog.words, Date.now().toString(36), learner.level), source: "learning_catalog" }); } catch (error) { if (!(error instanceof LearningCatalogError)) throw error; console.warn(`Catálogo indisponível, usando Professor EduQuest como contingência: ${error.message}`); }
    const context = learnerContext(learner, typeof previousLessonTitle === "string" ? previousLessonTitle : undefined);
    const instructions = missionTeacherInstructions(learner);
    try { const text = await generateOpenAIText({ temperature: 0.5, textFormat: missionJsonSchema, instructions, input: context }); return res.status(200).json({ lesson: normalizeLesson(parseJsonResponse(text), Date.now().toString(36)) }); } catch (error) { if (!(error instanceof InvalidMissionError)) throw error; const retryText = await generateOpenAIText({ temperature: 0.2, textFormat: missionJsonSchema, instructions: `${instructions}\nA tentativa anterior foi rejeitada porque: ${error.message} Gere uma missão inteiramente nova. Revise cada exercício antes de responder e nunca deixe prompt vazio.`, input: context }); return res.status(200).json({ lesson: normalizeLesson(parseJsonResponse(retryText), Date.now().toString(36)) }); }
  } catch (error: unknown) {
    if (error instanceof InvalidMissionError) { const requestId = `mission-${Date.now().toString(36)}`; console.error(`[${requestId}] Missão devolvida pela IA fora do contrato: ${error.message}`); return res.status(422).json({ error: `A IA gerou uma missão incompleta: ${error.message} Tente novamente. Código: AI_MISSION_INVALID. Rastreio: ${requestId}.`, diagnostic: { code: "AI_MISSION_INVALID", message: error.message, requestId } }); }
    const diagnostic = getAIDiagnostic(error); console.error(`[${diagnostic.requestId}] Erro ao criar missão por IA:`, error); return res.status(error instanceof OpenAIDiagnosticError ? error.status : 500).json({ error: `${diagnostic.message} Código: ${diagnostic.code}. Rastreio: ${diagnostic.requestId}.`, diagnostic });
  }
}
